### ISSUE TITLE
Add support OneOf from protobuf 2.6.0

### ISSUE THREAD

**Issue by arturgspb** [nnmatveev/idea-plugin-protobuf#54]
Feature is very useful for the realization of something like polymorphism.
OneOf docs: https://developers.google.com/protocol-buffers/docs/reference/java-generated#oneof

Changes version: https://groups.google.com/forum/#!msg/protobuf/lvI8-sWZbUY/2_a8LVDMi5YJ

**Comment by tcripps** [comment]
We owe @delkind a huge thanks for implementing oneof support.
