### ISSUE TITLE
Proto3 Not Supported

### ISSUE THREAD

**Issue by bionicrm** [nnmatveev/idea-plugin-protobuf#68]
It seems that the proto3 syntax is unsupported, as errors occur when I remove `required` and `optional` keywords, as required by proto3. While it is still in alpha, basic support for it may at least alleviate the littering of errors all over the file.

**Comment by wenerme** [comment]
Also not support grpc

```
syntax = "proto3";

option java_package = "play";

package play;


// The request message containing the user's name.
message HelloRequest {
	string name = 1;
}

// The response message containing the greetings
message HelloReply {
	string message = 1;
}

// The greeter service definition.
service Greeter {
	// Sends a greeting
	rpc SayHello (HelloRequest) returns (HelloReply) {}
	rpc SayHelloToThem(HelloRequest) returns (stream HelloReply) {}
	rpc SayHelloToAll(stream HelloRequest) returns (stream HelloReply) {}
}
```

**Comment by IceMan81** [comment]
It would be nice to have support for proto3. Thanks for the work you have put in to create this plugin.

**Comment by ramtej** [comment]
+1 for proto3 support

**Comment by akaspin** [comment]
+1

**Comment by flzyup** [comment]
+1

**Comment by mwitkow-io** [comment]
Pretty please :)

**Comment by depend** [comment]
+1

**Comment by kshchepanovskyi** [comment]
+1

![image](https://cloud.githubusercontent.com/assets/4040120/10268079/126b9328-6ab6-11e5-9236-1aa3631940c0.png)

**Comment by leebird** [comment]
+1. Thanks!

**Comment by IceMan81** [comment]
@tcripps Thanks a lot for this fix!

**Comment by ramtej** [comment]
Thanks !
