### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by kshchepanovskyi** [nnmatveev/idea-plugin-protobuf#83]
What about new release? Latest version I can install for IntelliJ IDEA is 0.5.9 - released almost year ago, it does not support proto3 and a lot of other stuff.

**Comment by moperacz** [comment]
+1

**Comment by xuwei-k** [comment]
+1

**Comment by tayama0324** [comment]
+1

**Comment by kmizu** [comment]
+1

**Comment by cirocosta** [comment]
:+1:

**Comment by zackangelo** [comment]
+1

**Comment by miclefebvre** [comment]
+1

**Comment by ehoule** [comment]
+1

**Comment by pgr0ss** [comment]
@tcripps Any chance you can release a new version?

**Comment by GingerGeek** [comment]
+1

**Comment by ouyangkongtong** [comment]
+1

**Comment by ewized** [comment]
+1

**Comment by kshchepanovskyi** [comment]
@tcripps Thank you!

**Comment by miclefebvre** [comment]
When will it be released ton the intellij plugin website ?

**Comment by tcripps** [comment]
The release is still a placeholder. There are still issues to address.
